---
- name: Remove an AKS Cluster
  hosts: all
  connection: local
  tasks:
  - name: Remove a managed Azure Container Services (AKS) instance
    azure_rm_aks:
      name: "{{ akscluster }}"
      resource_group: "{{ resourcegroup }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      state: absent
