---
- name: Create an AKS Cluster
  hosts: all
  connection: local
  tasks:
  - name: Create a managed Azure Container Services (AKS) instance
    azure_rm_aks:
      name: "{{ akscluster }}"
      location: "{{ location }}"
      resource_group: "{{ resourcegroup }}"
      dns_prefix: "{{ dns_prefix }}"
      kubernetes_version: "{{ kubernetes_version }}"
      linux_profile:
        admin_username: "{{ admin_username }}"
        ssh_key: "{{ sshkeys }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: "{{ poolname }}"
          count: "{{ poolcount }}"
          vm_size: "{{ vmsize }}"
      tags:
        Environment: "{{ env }}"
    register: aks
    
  - name: Obtain AKS Kube_Config file
    copy:
      content: "{{ aks.kube_config| to_json }}"
      dest: "/tmp/aks.json"
    #debug: 
      #msg: "{{ aks.kube_config | to_json(ensure_ascii=False) }}"
