- name: Create a Security Group in Azure
  hosts: all
  connection: local
  tasks:
  
    - name: Create a Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resourcegroup }}"
        name: "{{ sgname }}"
        purge_rules: yes
        rules:
           - name: "{{ item.key }}"
             protocol: "{{ item.value.protocol }}"
             destination_port_range: "{{ item.value.destination_port_range }}"
             access: "{{ item.value.access }}"
             priority: "{{item.value.priority}}"
             direction: "{{ item.value.direction }}"
        loop: "{{ lookup('dict', rules) }}"
