- name: Create a Virtual Machine in Azure
  hosts: all
  connection: local
  tasks:
  
    - name: Creating virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup }}"
        name: "{{ vmname }}"
        vm_size: "{{ vmsize }}"
        admin_username: "{{ username }}"
        #admin_password: "{{ password }}"
        ssh_password_enabled: False
        ssh_public_keys: 
           - path: /home/{{ username }}/.ssh/authorized_keys
             key_data: "{{ sshkeys }}" 
        image:
          offer: "{{ offer }}"
          publisher: "{{ publisher }}"
          sku: "{{ sku }}"
          version: "{{ version }}"
      register: vm
          
    - name: debug
      debug:
        var=vm.ansible_facts.azure_vm.tags._own_nic_
