- name: Create a Virtual Machine in Azure
  hosts: all
  connection: local
  tasks:
  
    - name: Creating virtual machine
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resourcegroup }}"
        name: "{{ vmname }}"
        managed_disk_type: "{{ disk_type }}"
        vm_size: "{{ vmsize }}"
        admin_username: "{{ username }}"
        ssh_password_enabled: False
        ssh_public_keys: 
           - path: /home/{{ username }}/.ssh/authorized_keys
             key_data: "{{ sshkeys }}" 
        tags:
          "name": "{{ vmname }}"
          "demo": "true"
          "os": "linux"
          "username": "{{ username }}"
        image:
          offer: "{{ offer }}"
          publisher: "{{ publisher }}"
          sku: "{{ sku }}"
          version: "{{ version }}"
      register: azurevm
           
    - name: Set Vars Status
      set_stats:
        data:
          sgname: "{{ azurevm.ansible_facts.azure_vm.tags._own_nsg_}}"
          vm_ip: "{{ azurevm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"

