- name: Create a Security Group in Azure
  hosts: all
  connection: local
  tasks:
  
    - name: Create a Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resourcegroup }}"
        name: "{{ sgname }}"
        purge_rules: yes
        rules:
           - name: "{{ item.key }}"
             protocol: "{{ item.protocol }}"
             destination_port_range: "{{ item.destination_port_range }}"
             access: "{{ item.access }}"
             priority: "{{item.priority}}"
             direction: "{{ item.direction }}"
        with_dict: "{{ rules }}"
